env_name: 'BipedalWalker-v3'
env_parameters:
  hardcore: true

seed: 42
exp_name: BipedalWalker-v3_medium
run_id: ??? # decided during execution

agent_type: "DDPG"

# PG
pg:
  train_episodes: 20000
  gamma: 0.98
  lr: 2e-3

# DDPG
ddpg:
  train_episodes: 20000
  gamma: 0.98
  actor_lr: 1e-3
  critic_lr: 1e-3
  tau: 1e-3
  batch_size: 64
  buffer_size: 200000
  normalize: false
  use_ou: false
  weight_decay: 0
  noise_std: 0.1
  uniform: true
  actor_layers: [512,512,256,64]
  critic_layers: [512,512,256,64]

testing: false
model_path: default

save_video: true
save_logging: true
save_model: true
use_wandb: false
silent: false

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .

