env_name: 'BipedalWalker-v3'
env_parameters:
  hardcore: true

seed: 100
exp_name: BipedalWalker-v3_medium
run_id: ??? # decided during execution

train_episodes: 20000
gamma: 0.99
lr: 2e-3

testing: false
model_path: default

save_video: true
save_logging: true
save_model: true
use_wandb: false
silent: false

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .

