env_name: 'BipedalWalker-v3'
env_parameters:
  hardcore: false

seed: 123
exp_name: BW_easy
run_id: ??? # decided during execution

train_episodes: 500
gamma: 0.99

# PG
lr_pg: 2e-5

# A2C
lr_a2c: 2e-5
ent_coeff: 0.01
normalize_a2c: false

# DDPG
actor_lr: 5e-5
critic_lr: 5e-4
tau: 0.001
batch_size: 64
buffer_size: 100000
normalize_ddpg: false

testing: false
model_path: default

save_video: true
save_logging: true
save_model: true
use_wandb: false
silent: true

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .


