env_name: 'LunarLander-v2'
env_parameters:
  continuous: true
  gravity: -9.81
  enable_wind: true
  wind_power: 15
  turbulence_power: 1.5

seed: 1
exp_name: LunarLander-v2_contin_medium
run_id: ??? # decided during execution
train_episodes: 2000
gamma: 0.98

# PG
lr_pg: 3e-4
layers: [512, 256, 64]

# DDPG
actor_lr: 1e-3
critic_lr: 1e-3
tau: 1e-3
batch_size: 64
buffer_size: 200000
normalize_ddpg: false
use_ou: false
weight_decay: 0
noise_std: 0.1
uniform: false
actor_layers: [512,256,64]
critic_layers: [512,256,64]

testing: false
model_path: default

save_video: true
save_logging: true
save_model: true
use_wandb: false
silent: true

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
